apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-santa-deployment
  labels:
    app: secret-santa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secret-santa
  template:
    metadata:
      labels:
        app: secret-santa
    spec:
      containers:
      - name: secret-santa
        image: samcolon/azure-pipeline-repo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: secret-santa-service
spec:
  type: LoadBalancer
  selector:
    app: secret-santa
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
